---

#1. Cette tache permet d'installer Apache (httpd)
- name: "apache installation"
  apt:
    name: "apache2"
    state: "present"

#2. Cette tache active le service apache
- name: "apache service activation"
  service:
    name: "apache2"
    state: "started"
    enabled: yes 

#3. Cette tache fait appel à un autre fichier de conf pour installer php 
- name: "install php packages"
  include_tasks: "php-install.yml"
  when: php_install|default(False)|bool 
