---
- name: "Requete dans une base"
  hosts: bdd1
  gather_facts: no
  tasks:
    - name: "compte le nombre de page dans le wiki"
      count_page:
        db_name: "mediawiki"
        request: "select count(*) from page;"
      register: resultat
    - debug: var=resultat

